---
language: ruby
rvm:
  - 2.2
  #- 2.1
  #- 2.0
  - 1.9.3

#cache:
#  directories:
#  - role-tester-ansible-master/.bootci/venv-ansible1.4
#  - role-tester-ansible-master/.bootci/venv-ansible1.4.4
#  - role-tester-ansible-master/.bootci/venv-ansible1.5.4
#  - role-tester-ansible-master/.bootci/venv-ansible1.6.1
#  - role-tester-ansible-master/.bootci/venv-ansible1.7.2
#  - role-tester-ansible-master/.bootci/venv-ansible1.8.4
#  - role-tester-ansible-master/.bootci/venv-ansible1.9.2
#  - role-tester-ansible-master/.bootci/venv-ansible2.0.0.2
#  - role-tester-ansible-master/.bootci/venv-ansible2.1.0.0
#  - role-tester-ansible-master/.bootci/venv-ansible2.5.1
#  - role-tester-ansible-master/vendor/bundle

env:
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.5.1

services:
  - docker

script:
  - wget -O- bit.ly/ansibletest | env sh -x

after_failure:
  - cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      secure: hzvxQ2kfh5NHvuxxWOGLvPI0afnQI2FqZMvWSTi82etpG7TCIowHt+dGSThGNBtg+DVZbc7TA98I4ndNy73C0d6fn5CY0GJF3UUU8RJ4gRaLM6Hw3KUnT7fcvBsgKcNV5lX9P+PUf2Us6RqI7WzYEbMgdrdRz4Kte5QrNQJh4cm3g15XkiMFYr0LMfFs4Ob0aOWU4XBg4OgEP2JVF2HTNzfGzO2mAplWKLLoX+IGXV+5gCPKslWvuz10sY71JGHxjTYLythTw4pROXR902Gh0L8wWYcYzvdJFYgwpSUzFUUbOa1IQ2cC6kM21pxgHKhemNrICqedGEvvo7CYSmO70dYV6A6BqbBJj2vLwqv9rvo7WG2f+1JGq7N5dblGx1g8uUP98rYnQt5lNJ86ojhEFJl4rrbwbU902Y47p5iZ4SyvnSuuxo+c2KTqfdFILdQdAhi260L6lyDT0UK4VVdrQoXZMCkP0T2PQrvDHMnCahGf8vX4VXzlvMPnrXUrDG9bvFmREtfbEmt6luQSO9hIl7Xsl3dCRihWcGDehwbDc96ZUvs1NH/bQabEyVczVF1gdzZpksLUsLv4AYjcKFwDhNb3gyJ0mSb5+F9yKFl1ECvfraHaNKrSx7SpwME7BcRdH+IWy57i0KfYUWwig4SBCikmJZtjul00UgsokwXvmOA=
