---
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3

# Use the new container infrastructure
sudo: false

services:
  - docker

script:
  - >
    wget -O- bit.ly/ansibletest | env
    DOCKER_IMAGES="debian:8 ubuntu:14.04
    ubuntu:16.04 fedora:20 fedora:24"
    ANSIBLE_VERSIONS="1.4 1.6.1 1.8.4 2.0.0.2 2.1.0.0"
    sh -x

after_failure:
  - cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      secure: hzvxQ2kfh5NHvuxxWOGLvPI0afnQI2FqZMvWSTi82etpG7TCIowHt+dGSThGNBtg+DVZbc7TA98I4ndNy73C0d6fn5CY0GJF3UUU8RJ4gRaLM6Hw3KUnT7fcvBsgKcNV5lX9P+PUf2Us6RqI7WzYEbMgdrdRz4Kte5QrNQJh4cm3g15XkiMFYr0LMfFs4Ob0aOWU4XBg4OgEP2JVF2HTNzfGzO2mAplWKLLoX+IGXV+5gCPKslWvuz10sY71JGHxjTYLythTw4pROXR902Gh0L8wWYcYzvdJFYgwpSUzFUUbOa1IQ2cC6kM21pxgHKhemNrICqedGEvvo7CYSmO70dYV6A6BqbBJj2vLwqv9rvo7WG2f+1JGq7N5dblGx1g8uUP98rYnQt5lNJ86ojhEFJl4rrbwbU902Y47p5iZ4SyvnSuuxo+c2KTqfdFILdQdAhi260L6lyDT0UK4VVdrQoXZMCkP0T2PQrvDHMnCahGf8vX4VXzlvMPnrXUrDG9bvFmREtfbEmt6luQSO9hIl7Xsl3dCRihWcGDehwbDc96ZUvs1NH/bQabEyVczVF1gdzZpksLUsLv4AYjcKFwDhNb3gyJ0mSb5+F9yKFl1ECvfraHaNKrSx7SpwME7BcRdH+IWy57i0KfYUWwig4SBCikmJZtjul00UgsokwXvmOA=
